-- Assessor parcel (tax) table: LA County Parcel Data load.
-- Join to property via apn (with hyphens); property.apn has hyphens.
-- No duplicated or same-meaning columns: address/geometry/year_built/sf/beds/baths come from property_address, property_geometry, mls_history.

CREATE TABLE IF NOT EXISTS assessor_parcel (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apn text NOT NULL,
  roll_year integer NOT NULL,
  city_tax_rate_area text,
  ain text,
  tax_rate_area_code text,
  property_use_type text,
  property_use_code text,
  recording_date date,
  land_value numeric,
  land_base_year integer,
  improvement_value numeric,
  improvement_base_year integer,
  total_value_land_improvement numeric,
  home_owners_exemption numeric,
  real_estate_exemption numeric,
  fixture_value numeric,
  fixture_exemption numeric,
  personal_property_value numeric,
  personal_property_exemption numeric,
  property_taxable text,
  total_value numeric,
  total_exemption numeric,
  taxable_value numeric,
  classification text,
  region_number text,
  cluster_code text,
  parcel_legal_description text,
  row_id text,
  objectid bigint,
  UNIQUE (apn, roll_year)
);

COMMENT ON TABLE assessor_parcel IS 'LA County Assessor Parcel (tax) data. Join to property on property.apn = assessor_parcel.apn (apn has hyphens). No address/geometry/size/beds—use property_address, property_geometry, mls_history.';
COMMENT ON COLUMN assessor_parcel.apn IS 'Assessor Parcel Number with hyphens (e.g. 2004-013-025). Matches property.apn.';
COMMENT ON COLUMN assessor_parcel.roll_year IS 'Roll year (e.g. 2021).';

CREATE INDEX IF NOT EXISTS idx_assessor_parcel_apn ON assessor_parcel (apn);
CREATE INDEX IF NOT EXISTS idx_assessor_parcel_roll_year ON assessor_parcel (roll_year);
